package untemplate

import scala.collection.{immutable,mutable}
import scala.util.matching.Regex.Match
import com.mchange.codegenutil

private val Suffix = "untemplate"
private val DotSuffix = "." + Suffix
private val DotSuffixLen = DotSuffix.length

private val DotScalaSuffix = ".scala"

final case class Result[+A](mbMetadata : Option[A], text : String ):
  override def toString() : String = text

opaque type UntemplateWarning = String

def toUntemplateWarning( s : String ) : UntemplateWarning = s

type Transpiler           = Function5[LocationPackage, Identifier, Customizer.Selector, UntemplateSource, Option[String], UntemplateScala]
type BlockPrinter         = Function0[String]
type OutputTransformer[A] = Function1[Result[A],Result[A]]

val DefaultTranspiler : Transpiler = defaultTranspile

// these are just examples
// val HeaderDelimiter    = "()[]~()>"

// val TextStartDelimiter = "()>"
// val TextEndDelimiter   = "<()"

// val EmbeddedExpressionDelimiter = "<()>"

// XXX: Not DRY! Added support for SideScala by just mimicking in parallel untemplate logic.
//      Perhaps the logic should be abstracted out in common
object UntemplateSource:
  final case class Metadata( mbLastModMetaOption : Option[Long] )
final case class UntemplateSource( provenance : String, lines : Vector[String] ):
  lazy val textLen : Int = lines.foldLeft(0)( (accum, next) => accum + next.length ) + lines.length * codegenutil.LineSep.length

// XXX: Not DRY! Added support for SideScala by just mimicking in parallel untemplate logic.
//      Perhaps the logic should be abstracted out in common
object SideScalaSource:
  final case class Metadata( mbLastModMetaOption : Option[Long] )
final case class SideScalaSource( provenance : String, lines : Vector[String] ):
  lazy val textLen : Int = lines.foldLeft(0)( (accum, next) => accum + next.length ) + lines.length * codegenutil.LineSep.length

def autogeneratedComment(mbSrcIdentifier : Option[String]) : String =
  def fromClause = mbSrcIdentifier.fold("")(si => s"from '${si}' ")
  val now = java.time.Instant.now()
  val formatter = java.time.format.DateTimeFormatter.ISO_INSTANT
  s"// DO NOT HAND EDIT -- Autogenerated ${fromClause}at ${formatter.format(now)}"

